/**
 * Re-export shim — universe commands from @solar/domain.
 */
export type {
  UniverseCommand,
  TickCommand,
  AddStarCommand,
  UpdateStarCommand,
  RemoveStarCommand,
  AttachStarCommand,
  DetachStarCommand,
  AddGroupCommand,
  UpdateGroupCommand,
  RemoveGroupCommand,
  AddToGroupCommand,
  RemoveFromGroupCommand,
  MoveToGroupCommand,
  SetSmallBodyFieldsCommand,
  UpdateSmallBodyFieldCommand,
  RemoveSmallBodyFieldCommand,
  SetProtoplanetaryDisksCommand,
  AddProtoplanetaryDiskCommand,
  UpdateProtoplanetaryDiskCommand,
  RemoveProtoplanetaryDiskCommand,
  SetNebulaeCommand,
  UpdateNebulaCommand,
  RemoveNebulaCommand,
  UpdateRingCommand,
  RemoveRingCommand,
  ReplaceSnapshotCommand,
  DomainEvent,
} from '@solar/domain';
